# Kitty — Catppuccin Mocha.
font_family JetBrains Mono
font_size 12.0

background #000000
background_opacity 0.70
transparent_background_colors #000000@0.70
hide_window_decorations yes
foreground #cdd6f4
cursor #f5e0dc
cursor_text_color #1e1e2e
selection_background #45475a
selection_foreground #cdd6f4

color0 #45475a
color1 #f38ba8
color2 #a6e3a1
color3 #f9e2af
color4 #89b4fa
color5 #f5c2e7
color6 #f5e0dc
color7 #bac2de
color8 #45475a
color9 #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #f5c2e7
color14 #94e2d5
color15 #cdd6f4

cursor_shape beam
cursor_blink_interval 0
enable_audio_bell no
window_margin_width 8
window_padding_width 10
confirm_os_window_close 0
shell fish

map ctrl+shift+t launch --cwd=current --type=tab
map ctrl+shift+w close_tab
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab
map ctrl+shift+enter launch --cwd=current
map ctrl+shift+d launch --cwd=current
map ctrl+shift+right next_window
map ctrl+shift+left previous_window
map ctrl+h neighboring_window left
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+l neighboring_window right
map ctrl+alt+n launch --cwd=current nvim
map ctrl+alt+g send_text all git status\r
